riot:
  api:
    key: ${RIOT_API_KEY}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true

  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update, 운영에서는 validate 또는 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 맞는 Dialect 사용
        format_sql: true
        show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug # SQL 디버그 정보 출력