name: Deploy To EC2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connects by SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Checking APPLICATION_PROPERTIES:"
            echo "$APPLICATION_PROPERTIES" | head -c 100
            cd /home/ubuntu/lol-hae-duo
            rm -rf src/main/resources/application.yml
            git pull origin dev
            echo "Writing application.yml..."
            printf "%s" "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            echo "Generated application.yml content:"
            cat src/main/resources/application.yml
            echo "Building application..."
            ./gradlew clean build
            echo "Stopping existing application on port 8080..."
            sudo fuser -k -n tcp 8080 || true
            echo "Starting application..."
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
            echo "Checking application logs:"
            tail -n 20 ./output.log