name: Deploy To EC2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connects by SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Checking APPLICATION_PROPERTIES:"
            echo "$APPLICATION_PROPERTIES"
            cd /home/ubuntu/lol-hae-duo
            rm -rf src/main/resources/application.yml
            git pull origin dev
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            cat src/main/resources/application.yml
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &