name: Deploy To EC2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connects by SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: |
            RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            MYSQL_URL=${{ secrets.MYSQL_URL }}
            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          script_stop: true
          script: |
            cd ~/lol-hae-duo
          
            if [ -d .git ]; then
              git reset --hard
              git pull origin dev
            else
              git clone https://github.com/team-summoner/lol-hae-duo.git .
              git checkout dev
            fi
          
            ./gradlew clean build
            pkill -f 'java -jar' || true
            nohup java -jar -Dspring.profiles.active=prod build/libs/*SNAPSHOT.jar > app.log 2>&1 &